version: '3.5'

services:
  db:
    restart: always
    container_name: db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    image: postgres:14.3-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/001.sql
