version: '3.5'

services:
  api: 
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: api
    ports:
      - '3000:3000'
    depends_on:
      - db
    image: my-express-app

  db:
    restart: unless-stopped
    hostname: db
    container_name: db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    image: postgres:14.3-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/001.sql

